export { Contacto } from "./Contacto/Contacto";
export { Cotizacion } from "./Cotizacion/Cotizacion";
export { Confirmacion } from "./Cotizacion/Confirmacion";
export { PoliticaCalidad } from "./Nosotros/PoliticaCalidad";
export { CodigoEtica } from "./Nosotros/CodigoEtica";
export { Mineria } from "./Mercados/Mineria";
export { Forestal } from "./Mercados/Forestal";
export { Agricola } from "./Mercados/Agricola";
export { Siderurgica } from "./Mercados/Siderurgica";
export { Construccion } from "./Mercados/Construccion";
export { Ceramica } from "./Mercados/Ceramica";
export { Envases } from "./Mercados/Envases";
export { FibrasTextiles } from "./Mercados/FibrasTextiles";
export { Papel } from "./Mercados/Papel";
export { Vidrio } from "./Mercados/Vidrio";
export { AboutUs } from "./Nosotros/AboutUs";
export { Solutions } from "./Soluciones /Solutions";
export { MaquinasEnvolvedoras } from "./Soluciones /MaquinasEnvolvedoras";
export { FilmEmbalaje } from "./Soluciones /FilmEmbalaje";
export { Zunchos } from "./Soluciones /Zunchos";
export { Airpads } from "./Soluciones /Airpads";
export { Markets } from "./Mercados/Markets";
export { Home } from "./Home/Home";
export { Products } from "./Productos/Products";
export { ProductDetails } from "./Productos/ProductDetails";
export { ServicioTecnico } from "./ServicioTecnico/ServicioTecnico";
